//GET https://reqres.in/api/users

//GET https://localhost:5001/api/questions

//POST https://localhost:5001/api/questions {"text":"name"}

//OPTIONS https://localhost:5001/api/questions

HEAD https://localhost:5001/api/questions